name: 错误反馈
description: 在使用过程中遇到问题时，请选择该模板提交反馈
title: "[Bug]（在此简述碰到的问题）"
assignees: 17TheWord
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        ##请补全标题并填写下方内容

  - type: textarea
    id: run-env
    attributes:
      label: 运行环境
      description: 系统以及Java版本
      placeholder: Ubuntu 20.04 LTS OpenJDK-21
    validations:
      required: true

  - type: input
    id: queqiao-version
    attributes:
      label: 鹊桥版本号
      description: 0.0.1 或 0.0.2 等版本号
      placeholder: 0.0.1
    validations:
      required: true

  - type: input
    id: server-info
    attributes:
      label: 服务端信息
      description: 输入你的服务端jar的信息
      placeholder: purpur 1.20.1 2058
    validations:
      required: true

  - type: textarea
    id: reproduce-step
    attributes:
      label: 复现问题的步骤
      render: plain text
      description: 请提供复现问题的步骤，如果不能，请写明原因
      placeholder: |
        干净清晰的复现步骤有助于开发者更快定位问题所在，你所遇到的问题也会获得更高的优先级.

        示例步骤:
        1. 开启服务器
        3. 建立 正向/反向 Websocket 连接
        4. 接收/解析 ... 消息失败
        5. 发现问题
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 错误日志
      render: plain text
      description: 请提供完整的错误日志，以便开发者更快定位问题所在
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 截图
      description: 如果可以，提交截图更有助于我们分析问题

  - type: textarea
    id: additional-context
    attributes:
      label: 备注
      description: 添加你认为有必要的信息
