name: QueQiao
version: ${version}
main: com.github.theword.queqiao.QueQiao
api-version: ${api_version}
authors: [ 17TheWord ]
description: ${description}
website: https://github.com/17TheWord/QueQiao
commands:
  queqiao:
    description: 鹊桥命令
    permission: queqiao
    permission-message: 您没有执行命令的权限